proc MyGeo(string $geo)
{
    if($geo == "cube"){
        polyCube -w 10 -h 3 -d 3 -sx 10 -sy 2 -sz 2 -ch 1;
    }
    else if($geo == "sphere"){
        polySphere -r 1 -sx 20 -sy 20 -ch 1;
    }
    else if($geo == "torus"){
        polyTorus -r 1 -sr 0.5 -tw 0 -sx 20 -sy 20 -ch 1;
    }
}

MyGeo("torus")



//=========================
//External function that runs MyGeo

proc MySuperScript(){

    //...
    MyGeo("cube");
    //...
}

MySuperScript;